on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'dist'

      - name: Run deploy
        uses: JayMeDotDot/aliyun-OSS-deployer@v1.0.0
        with:
          access-key-id: ${{ secrets.ALICLOUDOSS_KEY_ID }}
          access-key-secret: ${{ secrets.ALICLOUDOSS_KEY_SECRET }}
          region: 'oss-cn-shanghai'
          bucket: 'dd-blog-bucket'
          secure: true